/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.modulos.AutomatoFinitoPilha.screens;

/**
 *
 * @author michel
 */
public class PilhaProcessamentoPanel extends javax.swing.JPanel {
    javax.swing.JPanel JanelaExecucao;

    /**
     * Creates new form test1
     */
    public PilhaProcessamentoPanel(javax.swing.JPanel janela) {
        JanelaExecucao= janela;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_proces1 = new javax.swing.JLabel();
        r_e = new javax.swing.JTextField();
        AFND3_Titulo7 = new javax.swing.JLabel();
        processamento1 = new javax.swing.JPanel();
        validarPalavraPilha1 = new javax.swing.JLabel();
        t_e = new javax.swing.JLabel();

        setBackground(new java.awt.Color(70, 71, 74));

        t_proces1.setBackground(new java.awt.Color(70, 71, 74));
        t_proces1.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        t_proces1.setForeground(new java.awt.Color(255, 255, 255));
        t_proces1.setText("Processamento");

        r_e.setBackground(new java.awt.Color(255, 255, 255));

        AFND3_Titulo7.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        AFND3_Titulo7.setForeground(new java.awt.Color(255, 255, 255));
        AFND3_Titulo7.setText("<html><p style=\"padding-bottom: 16px;\">Autômato Pilha</p></html>");
        AFND3_Titulo7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        processamento1.setBackground(new java.awt.Color(196, 196, 196));
        processamento1.setPreferredSize(new java.awt.Dimension(360, 321));

        javax.swing.GroupLayout processamento1Layout = new javax.swing.GroupLayout(processamento1);
        processamento1.setLayout(processamento1Layout);
        processamento1Layout.setHorizontalGroup(
            processamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        processamento1Layout.setVerticalGroup(
            processamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        validarPalavraPilha1.setBackground(new java.awt.Color(51, 51, 51));
        validarPalavraPilha1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        validarPalavraPilha1.setForeground(new java.awt.Color(255, 255, 255));
        validarPalavraPilha1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        validarPalavraPilha1.setText("Validar Palavra");
        validarPalavraPilha1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        validarPalavraPilha1.setOpaque(true);
        validarPalavraPilha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validarPalavraPilha1MouseClicked(evt);
            }
        });

        t_e.setBackground(new java.awt.Color(70, 71, 74));
        t_e.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        t_e.setForeground(new java.awt.Color(255, 255, 255));
        t_e.setText("Entrada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(validarPalavraPilha1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t_e)
                        .addGap(67, 67, 67)
                        .addComponent(r_e, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(processamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_proces1)
                        .addComponent(AFND3_Titulo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(AFND3_Titulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(t_proces1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(processamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_e, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_e, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(validarPalavraPilha1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void validarPalavraPilha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validarPalavraPilha1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_validarPalavraPilha1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AFND3_Titulo7;
    private javax.swing.JPanel processamento1;
    private javax.swing.JTextField r_e;
    private javax.swing.JLabel t_e;
    private javax.swing.JLabel t_proces1;
    private javax.swing.JLabel validarPalavraPilha1;
    // End of variables declaration//GEN-END:variables
}
