/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.modulos.AutomatoFinitoNaoDeterministico.screens;

import java.util.HashMap;
import main.modulos.AutomatoFinitoNaoDeterministico.controllers.FndController;
import main.modulos.AutomatoFinitoNaoDeterministico.controllers.Injection;

/**
 *
 * @author michel
 */
public class FndProcessamentoPanel extends javax.swing.JPanel {

    javax.swing.JPanel JanelaExecucao;
    FndController controller = new FndController();

    /**
     * Creates new form test1
     */
    public FndProcessamentoPanel(javax.swing.JPanel janela) {
        JanelaExecucao = janela;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AFND3_Titulo4 = new javax.swing.JLabel();
        AFND3_TextFieldEntrada1 = new javax.swing.JTextField();
        processamento2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Retorno = new javax.swing.JTextArea();
        validarPalavraFND = new javax.swing.JLabel();
        AFND3_Titulo5 = new javax.swing.JLabel();
        AFND3_Titulo6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(28, 28, 28));

        jPanel1.setBackground(new java.awt.Color(28, 28, 28));
        jPanel1.setPreferredSize(new java.awt.Dimension(553, 633));

        AFND3_Titulo4.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 36)); // NOI18N
        AFND3_Titulo4.setForeground(new java.awt.Color(255, 255, 255));
        AFND3_Titulo4.setText("<html><p style=\"padding-bottom: 16px;\">Autômato FND</p></html>");
        AFND3_Titulo4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        AFND3_TextFieldEntrada1.setBackground(new java.awt.Color(255, 255, 255));
        AFND3_TextFieldEntrada1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        AFND3_TextFieldEntrada1.setForeground(new java.awt.Color(0, 0, 0));
        AFND3_TextFieldEntrada1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AFND3_TextFieldEntrada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFND3_TextFieldEntrada1ActionPerformed(evt);
            }
        });

        processamento2.setBackground(new java.awt.Color(0, 0, 0));

        Retorno.setBackground(new java.awt.Color(0, 0, 0));
        Retorno.setColumns(20);
        Retorno.setForeground(new java.awt.Color(255, 255, 255));
        Retorno.setRows(5);
        jScrollPane1.setViewportView(Retorno);

        javax.swing.GroupLayout processamento2Layout = new javax.swing.GroupLayout(processamento2);
        processamento2.setLayout(processamento2Layout);
        processamento2Layout.setHorizontalGroup(
            processamento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processamento2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addContainerGap())
        );
        processamento2Layout.setVerticalGroup(
            processamento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processamento2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );

        validarPalavraFND.setBackground(new java.awt.Color(51, 51, 51));
        validarPalavraFND.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        validarPalavraFND.setForeground(new java.awt.Color(255, 255, 255));
        validarPalavraFND.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        validarPalavraFND.setText("Validar Palavra");
        validarPalavraFND.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        validarPalavraFND.setOpaque(true);
        validarPalavraFND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validarPalavraFNDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                validarPalavraFNDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                validarPalavraFNDMouseExited(evt);
            }
        });

        AFND3_Titulo5.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 22)); // NOI18N
        AFND3_Titulo5.setForeground(new java.awt.Color(255, 255, 255));
        AFND3_Titulo5.setText("Entrada");

        AFND3_Titulo6.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        AFND3_Titulo6.setForeground(new java.awt.Color(255, 255, 255));
        AFND3_Titulo6.setText("Processamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AFND3_Titulo6)
                        .addComponent(AFND3_Titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(processamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AFND3_Titulo5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AFND3_TextFieldEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(validarPalavraFND, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(AFND3_Titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AFND3_Titulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(processamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFND3_TextFieldEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AFND3_Titulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(validarPalavraFND, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AFND3_TextFieldEntrada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFND3_TextFieldEntrada1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AFND3_TextFieldEntrada1ActionPerformed

    private void validarPalavraFNDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validarPalavraFNDMouseEntered
        validarPalavraFND.setBackground(validarPalavraFND.getBackground().brighter().brighter());
    }//GEN-LAST:event_validarPalavraFNDMouseEntered

    private void validarPalavraFNDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validarPalavraFNDMouseExited
        validarPalavraFND.setBackground(validarPalavraFND.getBackground().darker().darker());
    }//GEN-LAST:event_validarPalavraFNDMouseExited

    private void validarPalavraFNDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validarPalavraFNDMouseClicked
        String temp = "";
        HashMap map = Injection.getMap();
        Injection.getAutomato().config.clear();
        Injection.getAutomato().reconhecer(AFND3_TextFieldEntrada1.getText());
        StringBuilder text = new StringBuilder();
        for (String x : Injection.getAutomato().config) {
            if (x.indexOf("[") != -1) {
                temp = x.substring(x.indexOf("["), x.indexOf("]") + 1).replace("[", "").replace("]", "");
                x = x.replace("[" + temp + "]", "[" + Injection.getMap().get(Integer.valueOf(temp)) + "]");
            }
            text.append(x);
            text.append("\n");
        }
        Retorno.setText(text.toString());
    }//GEN-LAST:event_validarPalavraFNDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AFND3_TextFieldEntrada1;
    private javax.swing.JLabel AFND3_Titulo4;
    private javax.swing.JLabel AFND3_Titulo5;
    private javax.swing.JLabel AFND3_Titulo6;
    private javax.swing.JTextArea Retorno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel processamento2;
    private javax.swing.JLabel validarPalavraFND;
    // End of variables declaration//GEN-END:variables
}
