/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.modulos.AutomatoFinitoNaoDeterministico.screens;



import java.awt.CardLayout;
import java.awt.Color;
import java.awt.font.TextAttribute;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
/**
 *
 * @author thiag
 */
public class FNDScreen extends javax.swing.JFrame {

    public CardLayout cl;
    
    /**
     * Creates new form Padrao
     */
    public FNDScreen() {
        super("LFPrototipo");
        initComponents();
        this.JanelaVisivel.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        JanelaVisivel.setSize(1200, 700);
        JanelaVisivel.setLocation(100, 160);
        this.jLabel1.setBackground(Color.BLACK);
        cl = (CardLayout) JanelaExecucao.getLayout();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JanelaPrincipal = new javax.swing.JPanel();
        JanelaVisivel = new javax.swing.JInternalFrame();
        JanelaExecucao = new javax.swing.JPanel();
        Config_AFND = new javax.swing.JPanel();
        AFND2_InternalPanel = new javax.swing.JPanel();
        AFND2_LabelAlfabeto = new javax.swing.JLabel();
        AFND2_LabelEstadosFinais = new javax.swing.JLabel();
        AFND2_LabelEstados = new javax.swing.JLabel();
        AFND2_LabelEstadoInicial = new javax.swing.JLabel();
        AFND2_LabelTabelaTransicao = new javax.swing.JLabel();
        AFND2_TextFieldAlfabeto = new javax.swing.JTextField();
        AFND2_jScrollPane2 = new javax.swing.JScrollPane();
        AFND2_jTable1 = new javax.swing.JTable();
        AFND2_TextFieldEstados = new javax.swing.JTextField();
        AFND2_TextFieldEstadoInicial = new javax.swing.JTextField();
        AFND2_TextFieldEstadosFinais = new javax.swing.JTextField();
        AFND2_JButtonSalvarAutomato = new javax.swing.JButton();
        AFND2_Titulo = new javax.swing.JLabel();
        AFND2_HelpIcon = new javax.swing.JLabel();
        AFND2_Titulo1 = new javax.swing.JLabel();
        AFND2_LabelProcessarAutomato = new javax.swing.JLabel();
        Inicio_AFND = new javax.swing.JPanel();
        InicioAFND_1 = new javax.swing.JPanel();
        AFND1_LabelAutomatoFND = new javax.swing.JLabel();
        AFND1_LabelImportarAutomato = new javax.swing.JLabel();
        AFND1_LabelHelpIcon = new javax.swing.JLabel();
        AFND1_LabelNovoAutomato = new javax.swing.JLabel();
        Result_AFND = new javax.swing.JPanel();
        AFND3_Titulo4 = new javax.swing.JLabel();
        AFND3_HelpIcon1 = new javax.swing.JLabel();
        AFND3_Titulo5 = new javax.swing.JLabel();
        AFND3_jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        AFND3_Titulo6 = new javax.swing.JLabel();
        AFND3_TextFieldEntrada1 = new javax.swing.JTextField();
        AFND3_JLabelProcessarAutomato = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        JanelaPrincipal.setBackground(new java.awt.Color(70, 71, 74));
        JanelaPrincipal.setForeground(new java.awt.Color(70, 71, 74));

        JanelaVisivel.setBackground(new java.awt.Color(1, 2, 3));
        JanelaVisivel.setVisible(true);

        JanelaExecucao.setBackground(new java.awt.Color(70, 71, 74));
        JanelaExecucao.setForeground(new java.awt.Color(255, 255, 255));
        JanelaExecucao.setLayout(new java.awt.CardLayout());

        Config_AFND.setBackground(new java.awt.Color(70, 71, 74));

        AFND2_LabelAlfabeto.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        AFND2_LabelAlfabeto.setForeground(new java.awt.Color(255, 255, 255));
        AFND2_LabelAlfabeto.setText("Alfabeto");

        AFND2_LabelEstadosFinais.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        AFND2_LabelEstadosFinais.setForeground(new java.awt.Color(255, 255, 255));
        AFND2_LabelEstadosFinais.setText("Estados Finais");

        AFND2_LabelEstados.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        AFND2_LabelEstados.setForeground(new java.awt.Color(255, 255, 255));
        AFND2_LabelEstados.setText("Estados");

        AFND2_LabelEstadoInicial.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        AFND2_LabelEstadoInicial.setForeground(new java.awt.Color(255, 255, 255));
        AFND2_LabelEstadoInicial.setText("Estado Inicial");

        AFND2_LabelTabelaTransicao.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        AFND2_LabelTabelaTransicao.setForeground(new java.awt.Color(255, 255, 255));
        AFND2_LabelTabelaTransicao.setText("Tabela de transição");

        AFND2_TextFieldAlfabeto.setBackground(new java.awt.Color(255, 255, 255));
        AFND2_TextFieldAlfabeto.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        AFND2_TextFieldAlfabeto.setForeground(new java.awt.Color(0, 0, 0));
        AFND2_TextFieldAlfabeto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AFND2_TextFieldAlfabeto.setText("0,1");
        AFND2_TextFieldAlfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFND2_TextFieldAlfabetoActionPerformed(evt);
            }
        });
        AFND2_TextFieldAlfabeto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AFND2_TextFieldAlfabetoKeyReleased(evt);
            }
        });

        AFND2_jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        AFND2_jScrollPane2.setViewportView(AFND2_jTable1);

        AFND2_TextFieldEstados.setBackground(new java.awt.Color(255, 255, 255));
        AFND2_TextFieldEstados.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        AFND2_TextFieldEstados.setForeground(new java.awt.Color(0, 0, 0));
        AFND2_TextFieldEstados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AFND2_TextFieldEstados.setText("[q0,q1]");

        AFND2_TextFieldEstadoInicial.setBackground(new java.awt.Color(255, 255, 255));
        AFND2_TextFieldEstadoInicial.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        AFND2_TextFieldEstadoInicial.setForeground(new java.awt.Color(0, 0, 0));
        AFND2_TextFieldEstadoInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AFND2_TextFieldEstadoInicial.setText("q0");
        AFND2_TextFieldEstadoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFND2_TextFieldEstadoInicialActionPerformed(evt);
            }
        });

        AFND2_TextFieldEstadosFinais.setBackground(new java.awt.Color(255, 255, 255));
        AFND2_TextFieldEstadosFinais.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        AFND2_TextFieldEstadosFinais.setForeground(new java.awt.Color(0, 0, 0));
        AFND2_TextFieldEstadosFinais.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AFND2_TextFieldEstadosFinais.setText("q1");
        AFND2_TextFieldEstadosFinais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFND2_TextFieldEstadosFinaisActionPerformed(evt);
            }
        });

        AFND2_JButtonSalvarAutomato.setText("Salvar autômato");
        AFND2_JButtonSalvarAutomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFND2_JButtonSalvarAutomatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AFND2_InternalPanelLayout = new javax.swing.GroupLayout(AFND2_InternalPanel);
        AFND2_InternalPanel.setLayout(AFND2_InternalPanelLayout);
        AFND2_InternalPanelLayout.setHorizontalGroup(
            AFND2_InternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AFND2_InternalPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(AFND2_InternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AFND2_InternalPanelLayout.createSequentialGroup()
                        .addGroup(AFND2_InternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AFND2_LabelTabelaTransicao)
                            .addGroup(AFND2_InternalPanelLayout.createSequentialGroup()
                                .addComponent(AFND2_LabelAlfabeto)
                                .addGap(155, 155, 155)
                                .addComponent(AFND2_TextFieldAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AFND2_InternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(AFND2_InternalPanelLayout.createSequentialGroup()
                                    .addComponent(AFND2_LabelEstadosFinais)
                                    .addGap(89, 89, 89)
                                    .addComponent(AFND2_TextFieldEstadosFinais))
                                .addGroup(AFND2_InternalPanelLayout.createSequentialGroup()
                                    .addGroup(AFND2_InternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AFND2_LabelEstadoInicial)
                                        .addComponent(AFND2_LabelEstados))
                                    .addGap(96, 96, 96)
                                    .addGroup(AFND2_InternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AFND2_TextFieldEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AFND2_TextFieldEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(AFND2_InternalPanelLayout.createSequentialGroup()
                        .addComponent(AFND2_jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AFND2_JButtonSalvarAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        AFND2_InternalPanelLayout.setVerticalGroup(
            AFND2_InternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AFND2_InternalPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AFND2_InternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFND2_LabelAlfabeto)
                    .addComponent(AFND2_TextFieldAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AFND2_InternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AFND2_InternalPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(AFND2_LabelEstadosFinais))
                    .addComponent(AFND2_TextFieldEstadosFinais, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(AFND2_InternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AFND2_LabelEstadoInicial)
                    .addComponent(AFND2_TextFieldEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AFND2_InternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFND2_LabelEstados)
                    .addComponent(AFND2_TextFieldEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AFND2_InternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AFND2_InternalPanelLayout.createSequentialGroup()
                        .addComponent(AFND2_LabelTabelaTransicao)
                        .addGap(18, 18, 18)
                        .addComponent(AFND2_jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AFND2_JButtonSalvarAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        AFND2_Titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        AFND2_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        AFND2_Titulo.setText("<html><p style=\"padding-bottom: 16px;\">Autômato FND</p></html>");
        AFND2_Titulo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        AFND2_HelpIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AFND2_HelpIconMouseEntered(evt);
            }
        });

        AFND2_Titulo1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        AFND2_Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        AFND2_Titulo1.setText("Configuração");

        AFND2_LabelProcessarAutomato.setBackground(new java.awt.Color(0, 0, 0));
        AFND2_LabelProcessarAutomato.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        AFND2_LabelProcessarAutomato.setForeground(new java.awt.Color(255, 255, 255));
        AFND2_LabelProcessarAutomato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AFND2_LabelProcessarAutomato.setText("Processar autômato");
        AFND2_LabelProcessarAutomato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AFND2_LabelProcessarAutomato.setOpaque(true);
        AFND2_LabelProcessarAutomato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AFND2_LabelProcessarAutomatoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Config_AFNDLayout = new javax.swing.GroupLayout(Config_AFND);
        Config_AFND.setLayout(Config_AFNDLayout);
        Config_AFNDLayout.setHorizontalGroup(
            Config_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Config_AFNDLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(Config_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFND2_InternalPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AFND2_LabelProcessarAutomato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(Config_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Config_AFNDLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addGroup(Config_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AFND2_Titulo1)
                        .addGroup(Config_AFNDLayout.createSequentialGroup()
                            .addComponent(AFND2_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(AFND2_HelpIcon)))
                    .addContainerGap(239, Short.MAX_VALUE)))
        );
        Config_AFNDLayout.setVerticalGroup(
            Config_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Config_AFNDLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(AFND2_InternalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AFND2_LabelProcessarAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(Config_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Config_AFNDLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(Config_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(AFND2_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Config_AFNDLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(AFND2_HelpIcon)))
                    .addGap(57, 57, 57)
                    .addComponent(AFND2_Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(547, Short.MAX_VALUE)))
        );

        JanelaExecucao.add(Config_AFND, "Config AFND");

        Inicio_AFND.setBackground(new java.awt.Color(70, 71, 74));

        InicioAFND_1.setBackground(new java.awt.Color(70, 71, 74));

        AFND1_LabelAutomatoFND.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        AFND1_LabelAutomatoFND.setForeground(new java.awt.Color(255, 255, 255));
        AFND1_LabelAutomatoFND.setText("<html><p style=\"padding-bottom: 16px;\">Autômato FND</p></html>");
        AFND1_LabelAutomatoFND.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        AFND1_LabelImportarAutomato.setBackground(new java.awt.Color(0, 0, 0));
        AFND1_LabelImportarAutomato.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        AFND1_LabelImportarAutomato.setForeground(new java.awt.Color(255, 255, 255));
        AFND1_LabelImportarAutomato.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AFND1_LabelImportarAutomato.setText("Importar autômato");
        AFND1_LabelImportarAutomato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        AFND1_LabelHelpIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lf/studio/ícone - ajuda.png"))); // NOI18N

        AFND1_LabelNovoAutomato.setBackground(new java.awt.Color(0, 0, 0));
        AFND1_LabelNovoAutomato.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        AFND1_LabelNovoAutomato.setForeground(new java.awt.Color(255, 255, 255));
        AFND1_LabelNovoAutomato.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AFND1_LabelNovoAutomato.setText("Novo autômato");
        AFND1_LabelNovoAutomato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AFND1_LabelNovoAutomato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AFND1_LabelNovoAutomatoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InicioAFND_1Layout = new javax.swing.GroupLayout(InicioAFND_1);
        InicioAFND_1.setLayout(InicioAFND_1Layout);
        InicioAFND_1Layout.setHorizontalGroup(
            InicioAFND_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioAFND_1Layout.createSequentialGroup()
                .addGroup(InicioAFND_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioAFND_1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(AFND1_LabelAutomatoFND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AFND1_LabelHelpIcon))
                    .addGroup(InicioAFND_1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(InicioAFND_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AFND1_LabelImportarAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AFND1_LabelNovoAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        InicioAFND_1Layout.setVerticalGroup(
            InicioAFND_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioAFND_1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(InicioAFND_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFND1_LabelAutomatoFND, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InicioAFND_1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(AFND1_LabelHelpIcon)))
                .addGap(134, 134, 134)
                .addComponent(AFND1_LabelNovoAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AFND1_LabelImportarAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Inicio_AFNDLayout = new javax.swing.GroupLayout(Inicio_AFND);
        Inicio_AFND.setLayout(Inicio_AFNDLayout);
        Inicio_AFNDLayout.setHorizontalGroup(
            Inicio_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
            .addGroup(Inicio_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Inicio_AFNDLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InicioAFND_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Inicio_AFNDLayout.setVerticalGroup(
            Inicio_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
            .addGroup(Inicio_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Inicio_AFNDLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InicioAFND_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        JanelaExecucao.add(Inicio_AFND, "card4");

        AFND3_Titulo4.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        AFND3_Titulo4.setForeground(new java.awt.Color(255, 255, 255));
        AFND3_Titulo4.setText("<html><p style=\"padding-bottom: 16px;\">Autômato FND</p></html>");
        AFND3_Titulo4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        AFND3_HelpIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lf/studio/ícone - ajuda.png"))); // NOI18N
        AFND3_HelpIcon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AFND3_HelpIcon1MouseEntered(evt);
            }
        });

        AFND3_Titulo5.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        AFND3_Titulo5.setForeground(new java.awt.Color(255, 255, 255));
        AFND3_Titulo5.setText("Entrada");

        jList2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        AFND3_jScrollPane3.setViewportView(jList2);

        AFND3_Titulo6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        AFND3_Titulo6.setForeground(new java.awt.Color(255, 255, 255));
        AFND3_Titulo6.setText("Processamento");

        AFND3_TextFieldEntrada1.setBackground(new java.awt.Color(255, 255, 255));
        AFND3_TextFieldEntrada1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        AFND3_TextFieldEntrada1.setForeground(new java.awt.Color(0, 0, 0));
        AFND3_TextFieldEntrada1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AFND3_TextFieldEntrada1.setText("00001");
        AFND3_TextFieldEntrada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFND3_TextFieldEntrada1ActionPerformed(evt);
            }
        });

        AFND3_JLabelProcessarAutomato.setBackground(new java.awt.Color(0, 0, 0));
        AFND3_JLabelProcessarAutomato.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        AFND3_JLabelProcessarAutomato.setForeground(new java.awt.Color(255, 255, 255));
        AFND3_JLabelProcessarAutomato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AFND3_JLabelProcessarAutomato.setText("Validar palavra");
        AFND3_JLabelProcessarAutomato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AFND3_JLabelProcessarAutomato.setOpaque(true);

        javax.swing.GroupLayout Result_AFNDLayout = new javax.swing.GroupLayout(Result_AFND);
        Result_AFND.setLayout(Result_AFNDLayout);
        Result_AFNDLayout.setHorizontalGroup(
            Result_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Result_AFNDLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(AFND3_Titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AFND3_HelpIcon1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Result_AFNDLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(Result_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Result_AFNDLayout.createSequentialGroup()
                        .addGroup(Result_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AFND3_jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Result_AFNDLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(AFND3_Titulo5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AFND3_TextFieldEntrada1)))
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Result_AFNDLayout.createSequentialGroup()
                        .addComponent(AFND3_JLabelProcessarAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))))
            .addGroup(Result_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Result_AFNDLayout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(AFND3_Titulo6)
                    .addContainerGap(354, Short.MAX_VALUE)))
        );
        Result_AFNDLayout.setVerticalGroup(
            Result_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Result_AFNDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Result_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AFND3_Titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Result_AFNDLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(AFND3_HelpIcon1)))
                .addGap(124, 124, 124)
                .addComponent(AFND3_jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Result_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFND3_Titulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AFND3_TextFieldEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AFND3_JLabelProcessarAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(Result_AFNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Result_AFNDLayout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(AFND3_Titulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(537, Short.MAX_VALUE)))
        );

        JanelaExecucao.add(Result_AFND, "Result_AFND");

        Menu.setBackground(new java.awt.Color(27, 28, 29));
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setMaximumSize(new java.awt.Dimension(400, 560));
        Menu.setName(""); // NOI18N
        Menu.setPreferredSize(new java.awt.Dimension(400, 560));
        Menu.setLayout(new javax.swing.BoxLayout(Menu, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setBackground(new java.awt.Color(27, 28, 29));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(null);
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 560));

        jPanel3.setBackground(new java.awt.Color(70, 71, 74));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(344, 539));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 560));

        jLabel7.setBackground(new java.awt.Color(70, 71, 74));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("    Gramáticas LC");
        jLabel7.setMaximumSize(new java.awt.Dimension(344, 539));

        jLabel3.setBackground(new java.awt.Color(70, 71, 74));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("    Automato Pilha");
        jLabel3.setMaximumSize(new java.awt.Dimension(344, 539));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("    Expressões Regulares");
        jLabel6.setMaximumSize(new java.awt.Dimension(344, 539));
        jLabel6.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("    Máquinas de Turing");
        jLabel8.setMaximumSize(new java.awt.Dimension(344, 539));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("    Automato AFD");
        jLabel4.setMaximumSize(new java.awt.Dimension(344, 539));
        jLabel4.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("  LF Studio");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(344, 539));
        jLabel2.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("    Gramáticas Regulares");
        jLabel5.setMaximumSize(new java.awt.Dimension(344, 539));
        jLabel5.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("    Automato AFND");
        jLabel1.setMaximumSize(new java.awt.Dimension(344, 539));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel3);

        Menu.add(jScrollPane1);

        javax.swing.GroupLayout JanelaVisivelLayout = new javax.swing.GroupLayout(JanelaVisivel.getContentPane());
        JanelaVisivel.getContentPane().setLayout(JanelaVisivelLayout);
        JanelaVisivelLayout.setHorizontalGroup(
            JanelaVisivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JanelaVisivelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JanelaExecucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JanelaVisivelLayout.setVerticalGroup(
            JanelaVisivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JanelaVisivelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JanelaVisivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JanelaExecucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout JanelaPrincipalLayout = new javax.swing.GroupLayout(JanelaPrincipal);
        JanelaPrincipal.setLayout(JanelaPrincipalLayout);
        JanelaPrincipalLayout.setHorizontalGroup(
            JanelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JanelaPrincipalLayout.createSequentialGroup()
                .addComponent(JanelaVisivel)
                .addContainerGap())
        );
        JanelaPrincipalLayout.setVerticalGroup(
            JanelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JanelaVisivel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        getContentPane().add(JanelaPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AFND2_HelpIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AFND2_HelpIconMouseEntered
        
    }//GEN-LAST:event_AFND2_HelpIconMouseEntered

    private void AFND2_TextFieldAlfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFND2_TextFieldAlfabetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AFND2_TextFieldAlfabetoActionPerformed

    private void AFND2_TextFieldEstadosFinaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFND2_TextFieldEstadosFinaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AFND2_TextFieldEstadosFinaisActionPerformed

    private void AFND2_TextFieldEstadoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFND2_TextFieldEstadoInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AFND2_TextFieldEstadoInicialActionPerformed

    private void AFND2_JButtonSalvarAutomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFND2_JButtonSalvarAutomatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AFND2_JButtonSalvarAutomatoActionPerformed

    private void AFND3_HelpIcon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AFND3_HelpIcon1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AFND3_HelpIcon1MouseEntered

    private void AFND3_TextFieldEntrada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFND3_TextFieldEntrada1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AFND3_TextFieldEntrada1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        cl.show(JanelaExecucao, "card4");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void AFND1_LabelNovoAutomatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AFND1_LabelNovoAutomatoMouseClicked
        cl.show(JanelaExecucao,"Config AFND");
    }//GEN-LAST:event_AFND1_LabelNovoAutomatoMouseClicked

    private void AFND2_LabelProcessarAutomatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AFND2_LabelProcessarAutomatoMouseClicked
        cl.show(JanelaExecucao,"Result_AFND");
    }//GEN-LAST:event_AFND2_LabelProcessarAutomatoMouseClicked

    private void AFND2_TextFieldAlfabetoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AFND2_TextFieldAlfabetoKeyReleased
        recebeTexto();
        AFND2_jTable1.setEditingColumn(0);
        
    }//GEN-LAST:event_AFND2_TextFieldAlfabetoKeyReleased

    private ArrayList<String> recebeTexto(){
        
        String testa = AFND2_TextFieldAlfabeto.getText();
        String aux = "";
        ArrayList<String> possivelAlfabeto = new ArrayList<>();
        for (int i = 0; i < testa.length(); i++) {
            if(!String.valueOf(testa.charAt(i)).equals(",")){
            aux += testa.charAt(i);
            }else{
                possivelAlfabeto.add(aux);
                aux = "";
            }
        }
        return possivelAlfabeto;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FNDScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FNDScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FNDScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FNDScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FNDScreen().setVisible(true);
            }
        });
    }

    public JInternalFrame getjInternalFrame1() {
        return JanelaVisivel;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AFND1_LabelAutomatoFND;
    private javax.swing.JLabel AFND1_LabelHelpIcon;
    private javax.swing.JLabel AFND1_LabelImportarAutomato;
    private javax.swing.JLabel AFND1_LabelNovoAutomato;
    private javax.swing.JLabel AFND2_HelpIcon;
    private javax.swing.JPanel AFND2_InternalPanel;
    private javax.swing.JButton AFND2_JButtonSalvarAutomato;
    private javax.swing.JLabel AFND2_LabelAlfabeto;
    private javax.swing.JLabel AFND2_LabelEstadoInicial;
    private javax.swing.JLabel AFND2_LabelEstados;
    private javax.swing.JLabel AFND2_LabelEstadosFinais;
    private javax.swing.JLabel AFND2_LabelProcessarAutomato;
    private javax.swing.JLabel AFND2_LabelTabelaTransicao;
    private javax.swing.JTextField AFND2_TextFieldAlfabeto;
    private javax.swing.JTextField AFND2_TextFieldEstadoInicial;
    private javax.swing.JTextField AFND2_TextFieldEstados;
    private javax.swing.JTextField AFND2_TextFieldEstadosFinais;
    private javax.swing.JLabel AFND2_Titulo;
    private javax.swing.JLabel AFND2_Titulo1;
    private javax.swing.JScrollPane AFND2_jScrollPane2;
    private javax.swing.JTable AFND2_jTable1;
    private javax.swing.JLabel AFND3_HelpIcon1;
    private javax.swing.JLabel AFND3_JLabelProcessarAutomato;
    private javax.swing.JTextField AFND3_TextFieldEntrada1;
    private javax.swing.JLabel AFND3_Titulo4;
    private javax.swing.JLabel AFND3_Titulo5;
    private javax.swing.JLabel AFND3_Titulo6;
    private javax.swing.JScrollPane AFND3_jScrollPane3;
    private javax.swing.JPanel Config_AFND;
    private javax.swing.JPanel InicioAFND_1;
    private javax.swing.JPanel Inicio_AFND;
    private javax.swing.JPanel JanelaExecucao;
    private javax.swing.JPanel JanelaPrincipal;
    private javax.swing.JInternalFrame JanelaVisivel;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Result_AFND;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
