/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.modulos.AutomatoFinitoDeterministico.screens;

import main.LFStudio;

/**
 *
 * @author michel
 */
public class FdInicioPanel extends javax.swing.JPanel {
    javax.swing.JPanel JanelaExecucao;
    /**
     * Creates new form test1
     */
    public FdInicioPanel(    javax.swing.JPanel janela){
        this.JanelaExecucao = janela;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fdTitle1 = new javax.swing.JPanel();
        FD_LabelNovoAutomato = new javax.swing.JLabel();
        FD_LabelImportarAutomato3 = new javax.swing.JLabel();
        FD_LabelAutoma = new javax.swing.JLabel();

        setBackground(new java.awt.Color(70, 71, 74));

        fdTitle1.setBackground(new java.awt.Color(70, 71, 74));

        FD_LabelNovoAutomato.setBackground(new java.awt.Color(0, 0, 0));
        FD_LabelNovoAutomato.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        FD_LabelNovoAutomato.setForeground(new java.awt.Color(255, 255, 255));
        FD_LabelNovoAutomato.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FD_LabelNovoAutomato.setText("Novo autômato");
        FD_LabelNovoAutomato.setAlignmentX(5.0F);
        FD_LabelNovoAutomato.setAlignmentY(5.0F);
        FD_LabelNovoAutomato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FD_LabelNovoAutomato.setPreferredSize(new java.awt.Dimension(150, 22));
        FD_LabelNovoAutomato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FD_LabelNovoAutomatoMouseClicked(evt);
            }
        });

        FD_LabelImportarAutomato3.setBackground(new java.awt.Color(0, 0, 0));
        FD_LabelImportarAutomato3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        FD_LabelImportarAutomato3.setForeground(new java.awt.Color(255, 255, 255));
        FD_LabelImportarAutomato3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FD_LabelImportarAutomato3.setText("Importar autômato");
        FD_LabelImportarAutomato3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        FD_LabelAutoma.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        FD_LabelAutoma.setForeground(new java.awt.Color(255, 255, 255));
        FD_LabelAutoma.setText("<html><p style=\"padding-bottom: 16px;\">Autômato FD</p></html>");
        FD_LabelAutoma.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout fdTitle1Layout = new javax.swing.GroupLayout(fdTitle1);
        fdTitle1.setLayout(fdTitle1Layout);
        fdTitle1Layout.setHorizontalGroup(
            fdTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fdTitle1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(fdTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FD_LabelImportarAutomato3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FD_LabelNovoAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(fdTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fdTitle1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(FD_LabelAutoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        fdTitle1Layout.setVerticalGroup(
            fdTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fdTitle1Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(FD_LabelNovoAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FD_LabelImportarAutomato3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fdTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fdTitle1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(FD_LabelAutoma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(fdTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(fdTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FD_LabelNovoAutomatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FD_LabelNovoAutomatoMouseClicked
        LFStudio.cl.show(JanelaExecucao, "fdConfigPanel");
        // TODO add your handling code here:
    }//GEN-LAST:event_FD_LabelNovoAutomatoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FD_LabelAutoma;
    private javax.swing.JLabel FD_LabelImportarAutomato3;
    private javax.swing.JLabel FD_LabelNovoAutomato;
    private javax.swing.JPanel fdTitle1;
    // End of variables declaration//GEN-END:variables
}
