package main.modulos.GramaticasRegulares.screens;

import com.google.gson.Gson;
import java.awt.Font;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import main.LFStudio;
import main.modulos.GramaticasRegulares.screens.GRForm;
import main.modulos.GramaticasRegulares.controllers.GRController;
import main.modulos.GramaticasRegulares.domain.models.GR;

/**
 *
 * @author Grupo-03
 */
public class GRHome extends javax.swing.JPanel {

    javax.swing.JPanel JanelaExecucao;
    
    GRController grNovo = new GRController();
    
    /**
     * Creates new form GLCHome
     * @param janela
     */
    public GRHome(javax.swing.JPanel janela) {
        this.JanelaExecucao = janela;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fndTitle = new javax.swing.JPanel();
        labelTituloGR = new javax.swing.JLabel();
        labelNovaGR = new javax.swing.JLabel();
        labelImportarGR = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(28, 28, 28));
        setMaximumSize(new java.awt.Dimension(1024, 720));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setPreferredSize(new java.awt.Dimension(579, 648));

        fndTitle.setBackground(new java.awt.Color(28, 28, 28));
        fndTitle.setMaximumSize(new java.awt.Dimension(1024, 720));
        fndTitle.setPreferredSize(new java.awt.Dimension(1024, 720));

        labelTituloGR.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 48)); // NOI18N
        labelTituloGR.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloGR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloGR.setText("<html><p style=\"padding-bottom: 16px; font-size:30px;\">Gramáticas Regulares</p></html>");
        labelTituloGR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelTituloGRMouseEntered(evt);
            }
        });

        labelNovaGR.setBackground(new java.awt.Color(0, 0, 0));
        labelNovaGR.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 28)); // NOI18N
        labelNovaGR.setForeground(new java.awt.Color(255, 255, 255));
        labelNovaGR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNovaGR.setText("Nova GR");
        labelNovaGR.setAlignmentX(5.0F);
        labelNovaGR.setAlignmentY(5.0F);
        labelNovaGR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelNovaGR.setPreferredSize(new java.awt.Dimension(150, 22));
        labelNovaGR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelNovaGRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelNovaGRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelNovaGRMouseExited(evt);
            }
        });

        labelImportarGR.setBackground(new java.awt.Color(0, 0, 0));
        labelImportarGR.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 28)); // NOI18N
        labelImportarGR.setForeground(new java.awt.Color(255, 255, 255));
        labelImportarGR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImportarGR.setText("Importar GR");
        labelImportarGR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelImportarGR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImportarGRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelImportarGRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelImportarGRMouseExited(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(28, 28, 28));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fndTitleLayout = new javax.swing.GroupLayout(fndTitle);
        fndTitle.setLayout(fndTitleLayout);
        fndTitleLayout.setHorizontalGroup(
            fndTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fndTitleLayout.createSequentialGroup()
                .addGroup(fndTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelImportarGR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNovaGR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTituloGR))
                .addContainerGap())
            .addGroup(fndTitleLayout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        fndTitleLayout.setVerticalGroup(
            fndTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fndTitleLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(labelTituloGR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(labelNovaGR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelImportarGR)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fndTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fndTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelImportarGRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImportarGRMouseExited
        Font f = labelImportarGR.getFont();
        labelImportarGR.setFont(f.deriveFont(f.getStyle(), f.getSize2D()-4));
    }//GEN-LAST:event_labelImportarGRMouseExited

    private void labelImportarGRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImportarGRMouseEntered
        Font f = labelImportarGR.getFont();
        labelImportarGR.setFont(f.deriveFont(f.getStyle(), f.getSize2D()+4));
    }//GEN-LAST:event_labelImportarGRMouseEntered

    private void labelImportarGRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImportarGRMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        // fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Json File", "json"));

        fileChooser.setAcceptAllFileFilterUsed(false);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            String pathFile = fileChooser.getCurrentDirectory().toString() + "\\" + fileChooser.getSelectedFile().getName();
            File arquivoJson = new File(pathFile);

            if (!fileChooser.getSelectedFile().getName().endsWith(".json") || !arquivoJson.exists()) {
                JOptionPane.showMessageDialog(this,
                    "Arquivo Inválido para importar!", //mensagem
                    "Importação", // titulo da janela
                    JOptionPane.WARNING_MESSAGE);
            } else {
                Gson json = new Gson();
                try {
                    Reader fileJson = new FileReader( arquivoJson );
                    try {
                        GR gr = json.fromJson(fileJson, GR.class);
                        if (!gr.getTipo().equals(GR.Tooltip.GR)) {
                            JOptionPane.showMessageDialog(this,
                                "Tipo de Linguagem Inválido!", //mensagem
                                "Importação", // titulo da janela
                                JOptionPane.WARNING_MESSAGE);
                        } else {
                            // System.out.println(gr.toString());
                            GRForm.setFromImport(true);
                            GRForm.setNovoGRP(gr);
                            LFStudio.cl.show(JanelaExecucao, "grForm");
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this,
                            "Tipo de Linguagem Inválido!", //mensagem
                            "Importação", // titulo da janela
                            JOptionPane.WARNING_MESSAGE);
                    }
                    fileJson.close();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this,
                        "Erro ao abrir o arquivo!", //mensagem
                        "Importação", // titulo da janela
                        JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        // if (result == JFileChooser.CANCEL_OPTION) {
            // System.out.println("You pressed cancel");
            // }
    }//GEN-LAST:event_labelImportarGRMouseClicked

    private void labelNovaGRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNovaGRMouseExited
        Font f = labelNovaGR.getFont();
        labelNovaGR.setFont(f.deriveFont(f.getStyle(), f.getSize2D()-4));
    }//GEN-LAST:event_labelNovaGRMouseExited

    private void labelNovaGRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNovaGRMouseEntered
        Font f = labelNovaGR.getFont();
        labelNovaGR.setFont(f.deriveFont(f.getStyle(), f.getSize2D()+4));
    }//GEN-LAST:event_labelNovaGRMouseEntered

    private void labelNovaGRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNovaGRMouseClicked
        LFStudio.cl.show(JanelaExecucao, "grForm");
    }//GEN-LAST:event_labelNovaGRMouseClicked

    private void labelTituloGRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTituloGRMouseEntered

    }//GEN-LAST:event_labelTituloGRMouseEntered
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fndTitle;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelImportarGR;
    private javax.swing.JLabel labelNovaGR;
    private javax.swing.JLabel labelTituloGR;
    // End of variables declaration//GEN-END:variables
}
